name: Pos Tech Alura Tech Challenge Fase 2

on:
  workflow_dispatch:
  push:
    branches: 
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configuração Pipeline .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restauração de pacotes do projeto
      - run: dotnet restore ./GerenciadorAcervo.sln

      - name: Build
      - run: dotnet build ./GerenciadorAcervo.sln --configuration Release --no-restore

      - name: Publish
      - run: dotnet publish ./GerenciadorAcervo.sln --configuration Release --no-build
      

      

      

      

    

    
    
      

