name: Pos Tech Alura Tech Challenge Fase 2

on:
  workflow_dispatch:
  push:
    branches: 
    - master

env:
  AZURE_WEBAPP_NOME: postech-alura-tech-challenge-fase-2
  AZURE_WEBAPP_PACKAGE_CAMINHO: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configuração Pipeline .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restauração de pacotes do projeto
        run: dotnet restore ./GerenciadorAcervo.sln

      - name: Build
        run: dotnet build ./GerenciadorAcervo.sln -c Release --no-restore

      - name: Publish
        run: dotnet publish ./GerenciadorAcervo.sln -c Release --no-build -o '${{ env.AZURE_WEBAPP_PACKAGE_CAMINHO }}'
      
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NOME }}
          publish-profile: ${{ SECRETS.AZURE_PUBLISH_PERFIL }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_CAMINHO }}
